const actionTypes = {
  CAN_CASTLE: "CAN_CASTLE",
  GENERATE_CANDIDATE_MOVES: "GENERATE_CANDIDATE_MOVES",
  NEW_MOVE: "NEW_MOVE",
  CLEAR_CANDIDATE_MOVES: "CLEAR_CANDIDATE_MOVES",
  PROMOTION_CLOSE: "PROMOTION_CLOSE",
  PROMOTION_OPEN: "PROMOTION_OPEN",
};

export default actionTypes;
